
CREATE TABLE sentence (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	content TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,	
	document_id INTEGER NOT NULL,
	position INTEGER NOT NULL
) ENGINE=MyISAM;


CREATE TABLE document (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,	
	original_text TEXT
) ENGINE=MyISAM;


CREATE FULLTEXT INDEX sentence_idx ON sentence(content);